---
title: "Equine Influenza Efficacy Analysis"
author: "Olivia Rippee"
date: "`r Sys.Date()`"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE)

library(tidyverse)
#library(devtools)
#devtools::install_github("ABS-dev/MF")
library(MF)
library(epitools)
library(flextable)
library(ggplot2)
library(ggbreak)
```

```{r functions}

# P-value formatting function
format_p <- function(p) {
  if (is.na(p)) return(NA_character_)
  if (p < 0.0001) {
    output <- "< 0.0001"
  } else {output <- sprintf("%.4f", p)}}

# 5-number summary formatting function
format_integer <- function(x) {
  ifelse(x %% 1 == 0,
    formatC(x, format = "f", digits = 0),
    formatC(x, format = "f", digits = 2))}

```


```{r data}

data_2026 <- read.csv("your_efficacy_data_file.csv")
  
# Data cleaning that will vary based on input file and desired outcomes
# ---------------------------------------------------------------------
colnames(data_2026) <- gsub("\\.", "_", colnames(data_2026)) 

data_2026 <- data_2026 %>% 
  rename_with(~ gsub("_", "", .), .cols = Halter_) %>%
  filter(!is.na(Halter)) %>%
  filter(Halter != 69) %>%
  arrange(Halter, Day) %>%
  group_by(Halter) %>%
  mutate(
    DOC = max(Day[Study_Day == "DOC"], na.rm = TRUE),
    
    VI_PCR = case_when(
      VI_PCR == "Pos" ~ "Pos", VI_PCR == "Neg" ~ "Neg", VI_PCR == "Suspect" ~ "Neg", TRUE~NA),
    
    
    # Treatment Groups
    # -----------------
    Group = case_when(Group == 1 ~ "IVP", Group == 2 ~ "Control"),
 
    
    # Discharge
    # ---------
    Discharge_Status = case_when(
      Nasal_Discharge >= 2 | Ocular_Discharge >= 2 ~ "Yes",
      TRUE~"No"),
    Discharge_After_DOC = case_when(
      Discharge_Status == "Yes" & Day >= DOC ~ "Yes",
      TRUE~"No"),
    Discharge_Presence_Overall = if_else(any(Discharge_After_DOC == "Yes"), "Yes", "No"),
    
    
    # Discharge Duration
    # ------------------
    Discharge_Start_Day = {   # first discharge day after DOC (or NA if none)
      pos_days <- Day[Discharge_After_DOC == "Yes" & Day >= DOC]
      if(length(pos_days) > 0) min(pos_days) else NA_real_},
    
    Discharge_End_Day = {     # last discharge day after DOC (or NA if none)
      pos_days <- Day[Discharge_After_DOC == "Yes" & Day >= DOC]
      if(length(pos_days) > 0) max(pos_days) else NA_real_},
    
    Discharge_Duration = ifelse(
      !is.na(Discharge_Start_Day) & !is.na(Discharge_End_Day),
      Discharge_End_Day - Discharge_Start_Day + 1, 0),
    
    
    # Shedding Duration (PCR)
    # -----------------------
    Shedding_Start_Day = {   # first positive day after DOC (or NA if none)
      pos_days <- Day[VI_PCR == "Pos" & Day >= DOC]
      if(length(pos_days) > 0) min(pos_days) else NA_real_},
    Shedding_End_Day = {  # last positive day after DOC (or NA if none)
      pos_days <- Day[VI_PCR == "Pos" & Day >= DOC]
      if(length(pos_days) > 0) max(pos_days) else NA_real_},
    Shedding_Duration = ifelse(!is.na(Shedding_Start_Day) & !is.na(Shedding_End_Day),
                      Shedding_End_Day - Shedding_Start_Day + 1,  0),
    
    # Pyrexia Status
    # --------------
    Pyrexia_Status = case_when(
      Temperature >= 102.5 ~ "Yes", TRUE~"No"),
    Pyrexia_After_DOC = case_when(
      Pyrexia_Status == "Yes" & Day >= DOC ~ "Yes", TRUE~"No"),
    Pyrexia_Presence_Overall = if_else(any(Pyrexia_After_DOC == "Yes"), "Yes", "No"),
    
    
    # Pyrexia Duration
    # ----------------
    Pyrexia_Start_Day = {   # first positive day after DOC (or NA if none)
      pos_days <- Day[Pyrexia_After_DOC == "Yes" & Day >= DOC]
      if(length(pos_days) > 0) min(pos_days) else NA_real_},
    Pyrexia_End_Day = {  # last positive day after DOC (or NA if none)
      pos_days <- Day[Pyrexia_After_DOC == "Yes" & Day >= DOC]
      if(length(pos_days) > 0) max(pos_days) else NA_real_},
    Pyrexia_Duration = ifelse(!is.na(Pyrexia_Start_Day) & !is.na(Pyrexia_End_Day),
                      Pyrexia_End_Day - Pyrexia_Start_Day + 1,  0),
    
    
    # Titer Data
    # -----------
    HAI_Kentucky = case_when(
      HAI_Kentucky == "<2"   ~ 1,
      HAI_Kentucky == ">256" ~ 384,
      is.na(HAI_Kentucky) ~ NA_real_,
      TRUE ~ parse_number(HAI_Kentucky)),
    
    HAI_Richmond = case_when(
      HAI_Richmond == "<2"   ~ 1,
      HAI_Richmond == ">256" ~ 384,
      is.na(HAI_Richmond) ~ NA_real_,
      TRUE ~ parse_number(HAI_Richmond))) %>%
  
  ungroup()

# Establish Control group as reference
data_2026$Group <- factor(data_2026$Group, levels = c("Control", "IVP"))

data_individual <- data_2026 %>% 
  group_by(Halter) %>%
  slice_tail(n = 1) %>%    # keeps the last row per Halter
  ungroup()

# Establish Control group as reference
data_individual$Group <- factor(data_individual$Group, levels = c("Control", "IVP"))

# Verify duration is calculated correctly
# test <- data[, c("Halter", "Day", "VI_PCR", "Shedding_Duration", "Pyrexia_Duration")]

```

# Presence of Disease (Nasal or Ocular Discharge)

<br>

```{r presence discharge}

# Calculate counts and proportions
# ---------------------------------
summary_counts <- data_individual %>%
  group_by(Group) %>%
  summarize(
    Positive = sum(Discharge_Presence_Overall == "Yes"),
    Total = n(),
    Prop = Positive / Total,
    .groups = "drop")

# Create 2x2 contingency table
ct <- table(data_individual$Group, data_individual$Discharge_Presence_Overall)

# Relative risk with bootstrap CI
RR_result <- riskratio(ct, method = "boot", )

RR_estimate <- RR_result$measure[, "estimate"]
RR_lower    <- RR_result$measure[, "lower"]
RR_upper    <- RR_result$measure[, "upper"]
fisher_p    <- RR_result$p.value[, "fisher.exact"]

# Extract IVP prevented fraction (assuming IVP is 2nd row)
PF_ivp        <- 1 - RR_estimate[2]
Lower_CI_ivp  <- 1 - RR_upper[2]

# Create final summary table
summary_table <- summary_counts %>%
  mutate(Group = factor(Group, levels = c("IVP", "Control"))) %>%
  arrange(Group) %>%
  mutate(
    `Treatment Group` = ifelse(Group == "IVP", "1 = IVP", "2 = Control"),
    `Proportion of Positive Cases` =
      paste0(Positive, " / ", Total, " = ", sprintf("%.2f", Prop)),
    `Prevented Fraction` =
      ifelse(Group == "IVP", sprintf("%.2f", PF_ivp), ""),
    `Lower 95% Confidence Bound` =
      ifelse(Group == "IVP", sprintf("%.2f", Lower_CI_ivp), ""),
    `Fisher Exact p-value` = ifelse(Group == "IVP", format_p(fisher_p[2]), "")) %>%
  select(
    `Treatment Group`,
    `Proportion of Positive Cases`,
    `Prevented Fraction`,
    `Lower 95% Confidence Bound`,
    `Fisher Exact p-value`)

# Create flextable
flextable(summary_table) %>%
  set_caption("Clinical Disease Presence") %>%
  autofit() %>%
  align(align = "center", part = "all") %>%
  fit_to_width(max_width = 7) %>% 
  fontsize(size = 11, part = "all")

```

\pagebreak

# Duration of Disease (Nasal or Ocular Discharge)

<br>

```{r duration discharge}

# 5 number summary
# -------------------
summary_table_5num <- data_individual %>%
  mutate(Group = factor(Group, levels = c("IVP", "Control"))) %>%
  group_by(Group) %>%
  summarize(
    n = n(),
    Minimum = min(Discharge_Duration, na.rm = TRUE),
    `25th Percentile` = quantile(Discharge_Duration, 0.25, na.rm = TRUE),
    Median = median(Discharge_Duration, na.rm = TRUE),
    `75th Percentile` = quantile(Discharge_Duration, 0.75, na.rm = TRUE),
    Maximum = max(Discharge_Duration, na.rm = TRUE),
    .groups = "drop") %>%
  rename(
    `25th\nPercentile` = `25th Percentile`,
    `75th\nPercentile` = `75th Percentile`) %>%
  mutate(`Treatment Group` = ifelse(Group == "IVP", "1 = IVP", "2 = Control")) %>%
  select(`Treatment Group`, n:Maximum) %>%
  mutate(across(2:7, ~ format_integer(.x)))

flextable(summary_table_5num) %>%
  set_caption("Clinical Disease Duration Five-Number Summary") %>%
  autofit() %>%
  align(align = "center", part = "all") %>%
  fit_to_width(max_width = 7) %>% 
  fontsize(size = 11, part = "all")

```

<br>


```{r duration discharge mf}

# Calculate mitigated fraction
# -----------------------------
mf_boot <- MFBoot('Discharge_Duration ~ Group', data_individual, compare = c("Control", "IVP"), seed = 1234)


# Calculate Wilcoxon Rank Sum p-value
# ------------------------------------
test <- wilcox.test(Discharge_Duration ~ Group, data_individual)
p_value <- test$p.value


# MF, 95% lower bound, and p-value
# ---------------------------------
summary_table_mf <- tibble(
  `Mitigated Fraction` = round(mf_boot$stat[1,1], 2),
  `Lower 95% Confidence Bound` = round(mf_boot$stat[1,3], 2),
  `Wilcoxon Rank Sum p-value` = format_p(p_value))

flextable(summary_table_mf) %>%
  set_caption("Clinical Disease Duration Results") %>%
  autofit() %>%
  align(align = "center", part = "all") %>%
  fit_to_width(max_width = 7) %>% 
  fontsize(size = 11, part = "all")

```

<br>

```{r duration discharge boxplot}

ggplot(data_individual, aes(y = Group, x = Discharge_Duration, fill = Group)) +
  geom_boxplot(width = 0.6) +
  geom_dotplot(binaxis = "x", stackdir = "center", dotsize = 0.4, binwidth = 0.4, color = "black", fill = "black") +
  theme_minimal() +
  labs(
    title = "Clinical Disease Duration",
    #subtitle = paste0(
    #  "Mitigated Fraction = ", round(mf_boot$stat[1,1], 2),
    #  ", Lower 95% CI = ", round(mf_boot$stat[1,3], 2),
    #  ", p = ", format_p(p_value, 6)),
    x = "Duration (Days)", y = "Treatment Group") +
  theme(
    legend.position = "none",
    plot.title = element_text(face = "bold", size = 12, hjust = 0.5),
    plot.subtitle = element_text(size = 10))

```

\pagebreak

# Duration of Shedding (VI PCR)

<br>

```{r duration shedding}

# 5 number summary
# -------------------
summary_table_5num <- data_individual %>%
  mutate(Group = factor(Group, levels = c("IVP", "Control"))) %>%
  group_by(Group) %>%
  summarize(
    n = n(),
    Minimum = min(Shedding_Duration, na.rm = TRUE),
    `25th Percentile` = quantile(Shedding_Duration, 0.25, na.rm = TRUE),
    Median = median(Shedding_Duration, na.rm = TRUE),
    `75th Percentile` = quantile(Shedding_Duration, 0.75, na.rm = TRUE),
    Maximum = max(Shedding_Duration, na.rm = TRUE),
    .groups = "drop") %>%
  rename(
    `25th\nPercentile` = `25th Percentile`,
    `75th\nPercentile` = `75th Percentile`) %>%
  mutate(`Treatment Group` = ifelse(Group == "IVP", "1 = IVP", "2 = Control")) %>%
  select(`Treatment Group`, n:Maximum) %>%
  mutate(across(2:7, ~ format_integer(.x)))

flextable(summary_table_5num) %>%
  set_caption("Viral Shedding Duration Five-Number Summary") %>%
  autofit() %>%
  align(align = "center", part = "all") %>%
  fit_to_width(max_width = 7) %>% 
  fontsize(size = 11, part = "all")

```

<br>

```{r duration mf}

# Mitigated fraction
# -----------------------------
mf_boot <- MFBoot('Shedding_Duration ~ Group', data_individual, compare = c("Control", "IVP"), seed=1234)


# Wilcoxon Rank Sum p-value
# -------------------
test <- wilcox.test(Shedding_Duration ~ Group, data_individual)
p_value <- test$p.value


# MF, 95% lower bound, and p-value
# ---------------------------------
summary_table_mf <- tibble(
  `Mitigated Fraction` = round(mf_boot$stat[1,1], 2),
  `Lower 95% Confidence Bound` = round(mf_boot$stat[1,3], 2),
  `Wilcoxon Rank Sum p-value` = format_p(p_value))

flextable(summary_table_mf) %>%
  set_caption("Viral Shedding Duration Results") %>%
  autofit() %>%
  align(align = "center", part = "all") %>%
  fit_to_width(max_width = 7) %>% 
  fontsize(size = 11, part = "all")

```

<br>

```{r duration shedding boxplot}

ggplot(data_individual, aes(y = Group, x = Shedding_Duration, fill = Group)) +
  geom_boxplot(width = 0.6) +
  geom_dotplot(binaxis = "x", stackdir = "center", dotsize = 0.4, binwidth = 0.4, color = "black",fill = "black") +
  theme_minimal() +
  labs(
    title = "Viral Shedding Duration",
    #subtitle = paste0(
    #  "Mitigated Fraction = ", round(mf_boot$stat[1,1], 2),
    #  ", Lower 95% CI = ", round(mf_boot$stat[1,3], 2),
    #  ", p = ", format_p(p_value)),
    x = "Duration (Days)", y = "Treatment Group") +
  theme(legend.position = "none",
    plot.title = element_text(face = "bold", size = 12, hjust = 0.5),
    plot.subtitle = element_text(size = 10))

```

\pagebreak

# Incidence of Pyrexia (Rectal Temperatures)

<br>

```{r pyrexia presence}

# Calculate counts and proportions
# ---------------------------------
summary_counts <- data_individual %>%
  group_by(Group) %>%
  summarize(
    Positive = sum(Pyrexia_Presence_Overall == "Yes"),
    Total = n(),
    Prop = Positive / Total,
    .groups = "drop")


# Create 2x2 contingency table
ct <- table(data_individual$Group, data_individual$Pyrexia_Presence_Overall)

# Relative risk with bootstrap CI
RR_result <- riskratio(ct, method = "boot")

RR_estimate <- RR_result$measure[, "estimate"]
RR_lower    <- RR_result$measure[, "lower"]
RR_upper    <- RR_result$measure[, "upper"]
fisher_p    <- RR_result$p.value[, "fisher.exact"]

# Extract IVP prevented fraction (assuming IVP is 2nd row)
PF_ivp        <- 1 - RR_estimate[2]
Lower_CI_ivp  <- 1 - RR_upper[2]

# Create final summary table
summary_table <- summary_counts %>%
  mutate(Group = factor(Group, levels = c("IVP", "Control"))) %>%
  arrange(Group) %>%
  mutate(
    `Treatment Group` = ifelse(Group == "IVP", "1 = IVP", "2 = Control"),
    `Proportion of Positive Cases` =
      paste0(Positive, " / ", Total, " = ", sprintf("%.2f", Prop)),
    `Prevented Fraction` =
      ifelse(Group == "IVP", sprintf("%.2f", PF_ivp), ""),
    `Lower 95% Confidence Bound` =
      ifelse(Group == "IVP", sprintf("%.2f", Lower_CI_ivp), ""),
    `Fisher Exact p-value` = ifelse(Group == "IVP", format_p(fisher_p[2]), "")) %>%
  select(
    `Treatment Group`,
    `Proportion of Positive Cases`,
    `Prevented Fraction`,
    `Lower 95% Confidence Bound`,
    `Fisher Exact p-value`)

# Create flextable
flextable(summary_table) %>%
  set_caption("Pyrexia Presence") %>%
  autofit() %>%
  align(align = "center", part = "all") %>%
  fit_to_width(max_width = 7)  %>% 
  fontsize(size = 11, part = "all")

```

\pagebreak

# Duration of Pyrexia (Rectal Temperatures)

<br>

```{r pyrexia duration}

# 5 number summary
# -------------------
summary_table_5num <- data_individual %>%
  mutate(Group = factor(Group, levels = c("IVP", "Control"))) %>%
  group_by(Group) %>%
  summarize(
    n = n(),
    Minimum = min(Pyrexia_Duration, na.rm = TRUE),
    `25th Percentile` = quantile(Pyrexia_Duration, 0.25, na.rm = TRUE),
    Median = median(Pyrexia_Duration, na.rm = TRUE),
    `75th Percentile` = quantile(Pyrexia_Duration, 0.75, na.rm = TRUE),
    Maximum = max(Pyrexia_Duration, na.rm = TRUE),
    .groups = "drop") %>%
  rename(
    `25th\nPercentile` = `25th Percentile`,
    `75th\nPercentile` = `75th Percentile`) %>%
  mutate(`Treatment Group` = ifelse(Group == "IVP", "1 = IVP", "2 = Control")) %>%
  select(`Treatment Group`, n:Maximum) %>%
  mutate(across(2:7, ~ format_integer(.x)))

flextable(summary_table_5num) %>%
  set_caption("Pyrexia Duration Five-Number Summary") %>%
  autofit() %>%
  align(align = "center", part = "all") %>%
  fit_to_width(max_width = 7) %>% 
  fontsize(size = 11, part = "all")

```

<br>

```{r pyrexia duration mf}


# Mitigated fraction
# -------------------
mf_boot <- MFBoot('Pyrexia_Duration ~ Group', data_individual, compare = c("Control", "IVP"))


# Wilcoxon Rank Sum p-value
# --------------------------
test <- wilcox.test(Pyrexia_Duration ~ Group, data_individual)
p_value <- test$p.value


# MF, 95% lower bound, and p-value
# ---------------------------------
summary_table_mf <- tibble(
  `Mitigated Fraction` = round(mf_boot$stat[1,1], 2),
  `Lower 95% Confidence Bound` = round(mf_boot$stat[1,3], 2),
  `Wilcoxon Rank Sum p-value` = format_p(p_value))

flextable(summary_table_mf) %>%
  set_caption("Pyrexia Duration Results") %>%
  autofit() %>%
  align(align = "center", part = "all") %>%
  fit_to_width(max_width = 7) %>% 
  fontsize(size = 11, part = "all")

```

<br>

```{r pyrexia duration boxplot}

ggplot(data_individual, aes(y = Group, x = Pyrexia_Duration, fill = Group)) +
  geom_boxplot(width = 0.6) +
  geom_dotplot(binaxis = "x", stackdir = "center", dotsize = 0.4, binwidth = 0.4, color = "black",fill = "black") +
  theme_minimal() +
  labs(
    title = "Pyrexia Duration",
    #subtitle = paste0(
    #  "Mitigated Fraction = ", round(mf_boot$stat[1,1], 2),
    #  ", Lower 95% CI = ", round(mf_boot$stat[1,3], 2)),
    #  ", p = ", format_p(p_value)),
    x = "Duration (Days)", y = "Treatment Group") +
  scale_x_continuous(
    limits = c(0, 10),
    breaks = seq(0, 10, by = 2)) +
  theme(
    legend.position = "none",
    plot.title = element_text(face = "bold", size = 12, hjust = 0.5),
    plot.subtitle = element_text(size = 10))

```

\pagebreak

# Incidence of Kentucky Virus (HAI Titers)

<br>

```{r HAI titer Kentucky}

data_2026_KY_titer_incidence <- data_2026 %>%
  filter(!is.na(HAI_Kentucky)) %>%
  mutate(
    Kentucky_Pos = ifelse(HAI_Kentucky > 2, 1, 0),
    Group = factor(Group, levels = c("IVP", "Control")),
    Day = factor(Day))

data_2026_KY_titer_incidence_5day <- data_2026_KY_titer_incidence %>%
  filter(Day %in% c(0, 21, 35, 42, 49)) %>%
  mutate(
    Day = recode(as.character(Day), "35" = "35 (DOC)"),
    Day = factor(Day, levels = c("0", "21", "35 (DOC)", "42", "49")))

KY_titer_incidence_table <- data_2026_KY_titer_incidence_5day %>%
  group_by(Group, Day) %>%
  summarize(
    Positive_n = sum(Kentucky_Pos, na.rm = TRUE),
    Total = n(),
    Prop_Positive = Positive_n / Total,
    .groups = "drop") %>%
  mutate(Display = paste0(
    Positive_n, " / ", Total, " = ",
    sprintf("%.2f", Prop_Positive)))

KY_titer_incidence_wide <- KY_titer_incidence_table %>%
  select(Group, Day, Display) %>%
  pivot_wider(names_from = Day, values_from = Display) %>%
  arrange(Group) %>%
  mutate(`Treatment Group` = ifelse(Group == "IVP", "1 = IVP", "2 = Control")) %>%
  select(`Treatment Group`, `0`, `21`, `35 (DOC)`, `42`, `49`)

fisher_pvalues <- data_2026_KY_titer_incidence_5day %>%
  group_by(Day) %>%
  summarize(
    p_value = {
      tab <- table(Group, Kentucky_Pos)
      if (all(dim(tab) == c(2, 2))) {
        fisher.test(tab)$p.value
      } else {NA_real_}}, .groups = "drop") %>%
  mutate(p_value = sapply(p_value, format_p)) %>%
  pivot_wider(names_from = Day,
              values_from = p_value)

fisher_pvalues <- fisher_pvalues %>%
  mutate(`Treatment Group` = "Fisher Exact p-value") %>%
  select(`Treatment Group`, `0`, `21`, `35 (DOC)`, `42`, `49`)

KY_final_table <- bind_rows(KY_titer_incidence_wide, fisher_pvalues)

flextable(KY_final_table) %>%
  set_caption("Kentucky Virus HAI Titer Incidence") %>%
  autofit() %>%
  align(align = "center", part = "all") %>%
  fit_to_width(max_width = 7) %>% 
  fontsize(size = 10, part = "all")

```

<br>

```{r HAI titer Kentucky boxplot, fig.width=7}

ggplot(data_2026_KY_titer_incidence_5day ,
       aes(x = Group, y = HAI_Kentucky, fill = fct_rev(Group))) +
  geom_boxplot() +
  facet_wrap(~ Day, nrow = 1) +
  scale_y_break(c(100, 350)) +
  labs(title = "Kentucky Virus HAI Titers",
       y = "Kentucky HAI Titer",
       x = "Treatment Group") +
  theme(legend.position = "none",
    plot.title = element_text(face = "bold", size = 12, hjust = 0.5),
    plot.subtitle = element_text(size = 10))

```

\pagebreak

# Incidence of Richmond Virus (HAI Titers)

<br>

```{r HAI titer Richmond}

data_2026_RM_titer_incidence <- data_2026 %>%
  filter(!is.na(HAI_Richmond)) %>%
  mutate(
    Richmond_Pos = ifelse(HAI_Richmond > 2, 1, 0),
    Group = factor(Group, levels = c("IVP", "Control")),
    Day = factor(Day) )

data_2026_RM_titer_incidence_5day <- data_2026_RM_titer_incidence %>%
  filter(Day %in% c(0, 21, 35, 42, 49)) %>%
  mutate(
    Day = recode(as.character(Day), "35" = "35 (DOC)"),
    Day = factor(Day, levels = c("0", "21", "35 (DOC)", "42", "49")))

RM_titer_incidence_table <- data_2026_RM_titer_incidence_5day %>%
  group_by(Group, Day) %>%
  summarize(
    Positive_n = sum(Richmond_Pos, na.rm = TRUE),
    Total = n(),
    Prop_Positive = Positive_n / Total,
    .groups = "drop") %>%
  mutate(Display = paste0(
    Positive_n, " / ", Total, " = ",
    sprintf("%.2f", Prop_Positive)))

RM_titer_incidence_wide <- RM_titer_incidence_table %>%
  select(Group, Day, Display) %>%
  pivot_wider(names_from = Day, values_from = Display) %>%
  arrange(Group) %>%
  mutate(`Treatment Group` = ifelse(Group == "IVP", "1 = IVP", "2 = Control")) %>%
  select(`Treatment Group`, `0`, `21`, `35 (DOC)`, `42`, `49`)

fisher_pvalues <- data_2026_RM_titer_incidence_5day %>%
  group_by(Day) %>%
  summarize(
    p_value = {
      tab <- table(Group, Richmond_Pos)
      if (all(dim(tab) == c(2, 2))) {
        fisher.test(tab)$p.value
      } else {NA_real_}}, .groups = "drop") %>%
  mutate(p_value = sapply(p_value, format_p)) %>%
  pivot_wider(names_from = Day,
              values_from = p_value)

fisher_pvalues <- fisher_pvalues %>%
  mutate(`Treatment Group` = "Fisher Exact p-value") %>%
  select(`Treatment Group`, `0`, `21`, `35 (DOC)`, `42`, `49`)

RM_final_table <- bind_rows(RM_titer_incidence_wide, fisher_pvalues)

flextable(RM_final_table) %>%
  set_caption("Richmond Virus HAI Titer Incidence") %>%
  autofit() %>%
  align(align = "center", part = "all") %>%
  fit_to_width(max_width = 7) %>% 
  fontsize(size = 10, part = "all")

```

<br>

```{r HAI titer Richmond boxplot, fig.width=7}

ggplot(data_2026_RM_titer_incidence_5day,
       aes(x = Group, y = HAI_Richmond, fill = fct_rev(Group))) +
  geom_boxplot() +
  facet_wrap(~ Day, nrow = 1) +
  scale_y_break(c(100, 350)) +
  labs(title = "Richmond Virus HAI Titers",
       y = "Richmond HAI Titer",
       x = "Treatment Group") +
  theme(legend.position = "none",
    plot.title = element_text(face = "bold", size = 12, hjust = 0.5),
    plot.subtitle = element_text(size = 10))

```


